# Generated by Django 5.0.1 on 2024-01-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_receipreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_price',
            field=models.FloatField(default=0.0),
        ),
    ]
