# Generated by Django 5.0.1 on 2024-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_receipreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '<i class="fa-solid fa-star"></i>'), (2, '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>'), (3, '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>'), (4, '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>'), (5, '<i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>')], default=None),
        ),
    ]
