# Generated by Django 5.0.1 on 2024-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_receipreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipreview',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='receipreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipreview',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receipreview',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
