# Generated by Django 5.0.1 on 2024-01-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_receipreview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-12 12:12:12'),
            preserve_default=False,
        ),
    ]
