# Generated by Django 5.0.1 on 2024-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='receipe',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
