# Generated by Django 5.0.1 on 2024-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_cartitem_receipe_remove_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipreview',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
