# Generated by Django 5.0.1 on 2024-01-21 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_record_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
