# Generated by Django 5.0.1 on 2024-01-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_record_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
